server:
  port: 5006

spring:
  application:
    name: seat-service
  datasource:
    url: jdbc:mysql://localhost:3306/airline_seat_db
    username: root
    password: Viber+1014
  jpa:
    hibernate:
      ddl-auto: update




